// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmh7hnF9YOtKF6vCQFb7n_OYw0h3Uk6oc',
    appId: '1:300079214107:web:1f770198758593b74592be',
    messagingSenderId: '300079214107',
    projectId: 'shopone-62791',
    authDomain: 'shopone-62791.firebaseapp.com',
    storageBucket: 'shopone-62791.appspot.com',
    measurementId: 'G-915N51SFNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDItFBOVyMBg7Wz-evMUIM_jHcQY7c09i8',
    appId: '1:300079214107:android:750d92ec605fcaa54592be',
    messagingSenderId: '300079214107',
    projectId: 'shopone-62791',
    storageBucket: 'shopone-62791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2pJzgKTRPu3N7KPWCsH2QUPdvY2ud0w',
    appId: '1:300079214107:ios:1526486341e91dcf4592be',
    messagingSenderId: '300079214107',
    projectId: 'shopone-62791',
    storageBucket: 'shopone-62791.appspot.com',
    iosBundleId: 'com.dew.shopOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD2pJzgKTRPu3N7KPWCsH2QUPdvY2ud0w',
    appId: '1:300079214107:ios:1526486341e91dcf4592be',
    messagingSenderId: '300079214107',
    projectId: 'shopone-62791',
    storageBucket: 'shopone-62791.appspot.com',
    iosBundleId: 'com.dew.shopOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmh7hnF9YOtKF6vCQFb7n_OYw0h3Uk6oc',
    appId: '1:300079214107:web:13eb387009843aca4592be',
    messagingSenderId: '300079214107',
    projectId: 'shopone-62791',
    authDomain: 'shopone-62791.firebaseapp.com',
    storageBucket: 'shopone-62791.appspot.com',
    measurementId: 'G-WJ305NWD4N',
  );
}
